from typing import Any, Protocol, runtime_checkable

from app.domain.schemas.admins import AdminCreate, AdminInDB, AdminUpdate
from app.domain.schemas.devices import Device, DeviceCreate, DeviceUpdate
from app.domain.schemas.users import User, UserCreate, UserUpdate


@runtime_checkable
class IAdminRepository(Protocol):

    """
    
    Interface defining database operations for Admins.
    
    """

    async def get(self, id: Any) -> AdminInDB | None: ...
    async def get_by_username(self, username: str) -> AdminInDB | None: ...
    async def add(self, entity_in: AdminCreate) -> AdminInDB: ...
    async def update(self, db_obj: AdminInDB, obj_in: AdminUpdate) -> AdminInDB: ...
    async def delete(self, id: int) -> AdminInDB: ...


@runtime_checkable
class IUserRepository(Protocol):

    """
    
    Interface defining database operations for Users.
    
    """

    async def get(self, id: Any) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def get_multi(self, skip: int = 0, limit: int = 100) -> list[User]: ...
    async def get_users_over_quota(self) -> list[User]: ...
    async def get_all_users_count(self) -> int: ...
    async def get_near_quota_users_count(self) -> int: ...
    async def add(self, entity_in: UserCreate) -> User: ...
    async def update(self, db_obj: User, obj_in: UserUpdate) -> User: ...
    async def delete(self, id: int) -> User: ...


@runtime_checkable
class IDeviceRepository(Protocol):

    """
    
    Interface defining database operations for Devices.
    
    """

    async def get(self, id: Any) -> Device | None: ...
    async def get_multi(self, skip: int = 0, limit: int = 100) -> list[Device]: ...
    async def get_multi_by_user(self, user_id: int, skip: int = 0, limit: int = 100) -> list[Device]: ...
    async def get_enabled_devices_with_enabled_users(self) -> list[Device]: ...
    async def add(self, entity_in: DeviceCreate, client_identifier: str, protocol_data: dict[str, Any], ip_address: str | None) -> Device: ...
    async def update(self, db_obj: Device, obj_in: DeviceUpdate) -> Device: ...
    async def delete(self, id: int) -> Device: ...
    async def get_next_ip(self) -> str: ...
