from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class IVPNProvider(Protocol):

    """
    
    Interface defining capabilities for any VPN or tunneling protocol.
    
    """

    async def validate_interface(self) -> None: ...
    async def generate_credentials(self) -> tuple[str, dict[str, Any]]: ...
    async def provision_client(self, client_identifier: str, ip_address: str | None, protocol_data: dict[str, Any]) -> None: ...
    async def revoke_client(self, client_identifier: str, protocol_data: dict[str, Any]) -> None: ...
    async def get_client_config(self, client_identifier: str, ip_address: str | None, protocol_data: dict[str, Any]) -> str: ...
    async def get_usage_stats(self) -> dict[str, int]: ...
    async def list_peers(self) -> list[str]: ...
